### PR TITLE
Changes for python3+ compatibility

### PR DESCRIPTION
**Pull request by abbottLane**
It seems like the previous PR changes some of the python2 syntax to python3 syntax, but the repo was not python3 compatible. Issues like the use of cPickle (which doesn't exist in python3) remained. 

I'm able to run on python 2.7 or python 3.6.2 with the changes made here. Tested with the demo configs provided in the repo.

### CODE REVIEW

**Comment by jiesutd** [comment]
Hi @abbottLane, thanks for your contribution!

Yes, there are some syntax incompatible problems in the code, thanks for pointing out. 

I run your updated code (with the demo data) but get quite different results with my initial version. And the loss is 10 times less than my code. Besides, even the gold_num of entity is different, which is quite strange. Could you please compare the results of your version and my initial version in your computer?

Thanks again!

**Comment by abbottLane** [comment]
Thanks for pointing that out, I will look into it and figure out what's going on!

**Comment by abbottLane** [comment]
@jiesutd This latest push contains equivalent performance with the original in python2, but slightly different scores with python3:

Python3 - `python main.py --config demo.train.config` : 
```
Epoch: 0 training finished. Time: 3.84s, speed: 125.71st/s,  total loss: 5357.854598999023
totalloss: 5357.854598999023
gold_num =  208  pred_num =  50  right_num =  32
Dev: time: 0.24s, speed: 463.66st/s; acc: 0.8282, p: 0.6400, r: 0.1538, f: 0.2481
Exceed previous best f score: -10
Save current best model in file: sample_data/lstmcrf.0.model
gold_num =  345  pred_num =  116  right_num =  88
Test: time: 0.59s, speed: 319.07st/s; acc: 0.8977, p: 0.7586, r: 0.2551, f: 0.3818
```

Python3 - `python main.py --config demo.decode.config`
```
gold_num =  208  pred_num =  50  right_num =  32
raw: time:0.39s, speed:282.51st/s; acc: 0.8282, p: 0.6400, r: 0.1538, f: 0.2481
```

Python2 - `python main.py --config demo.train.config` : 
```
Epoch: 0 training finished. Time: 3.86s, speed: 125.29st/s,  total loss: 5464.09833527
totalloss: 5464.09833527
gold_num =  208  pred_num =  76  right_num =  41
Dev: time: 0.24s, speed: 464.22st/s; acc: 0.8317, p: 0.5395, r: 0.1971, f: 0.2887
Exceed previous best f score: -10
Save current best model in file: sample_data/lstmcrf.0.model
gold_num =  345  pred_num =  136  right_num =  69
Test: time: 0.62s, speed: 301.58st/s; acc: 0.8916, p: 0.5074, r: 0.2000, f: 0.2869
```
Python2 - `python main.py --config demo.decode.config` : 
```
gold_num =  208  pred_num =  76  right_num =  41
raw: time:0.40s, speed:279.17st/s; acc: 0.8317, p: 0.5395, r: 0.1971, f: 0.2887
```

Looking at my changes, I'm not entirely sure how to account for the diff between py2 and py3 performance. Perhaps this needs to be tested on a larger dataset like conll. I can run those experiments and get back to you.

**Comment by jiesutd** [comment]
That would be great! Appreciate your contribution. I am not sure if the difference between py2 and py3 comes from the random generator. I will merge this request once we confirm the difference of py2/py3 does not affect the final result too much on CoNLL data.

**Comment by jiesutd** [comment]
It seems the random generator is different between python 2 and 3. https://stackoverflow.com/questions/27191138/random-numbers-seeds-difference-in-python-2-and-3
This link shows that using `random.seed(a=42, version=1)` in Py3 can give the same random generator, could you please have a try?

Thanks!

**Comment by abbottLane** [comment]
Python 2.7 with 1 epoch of CoNLL NER data:
```
Epoch: 0/1
 Learning rate is setted as: 0.015
     Instance: 500; Time: 4.15s; loss: 4108.0815; acc: 5748.0/6902.0=0.8328
     Instance: 1000; Time: 3.96s; loss: 2456.8486; acc: 11819.0/13802.0=0.8563
     Instance: 1500; Time: 4.07s; loss: 2108.9716; acc: 17794.0/20537.0=0.8664
     Instance: 2000; Time: 4.22s; loss: 1906.2278; acc: 24337.0/27772.0=0.8763
     Instance: 2500; Time: 3.92s; loss: 1788.5728; acc: 30632.0/34685.0=0.8831
     Instance: 3000; Time: 4.08s; loss: 1914.3335; acc: 36951.0/41737.0=0.8853
     Instance: 3500; Time: 4.18s; loss: 1529.8658; acc: 42825.0/48213.0=0.8882
     Instance: 4000; Time: 4.03s; loss: 1598.2002; acc: 49017.0/55041.0=0.8906
     Instance: 4500; Time: 4.43s; loss: 1361.8032; acc: 55345.0/61894.0=0.8942
     Instance: 5000; Time: 4.27s; loss: 1404.9008; acc: 61548.0/68652.0=0.8965
     Instance: 5500; Time: 4.29s; loss: 1256.4086; acc: 67573.0/75185.0=0.8988
     Instance: 6000; Time: 3.87s; loss: 1379.4877; acc: 73826.0/81995.0=0.9004
     Instance: 6500; Time: 3.88s; loss: 1161.6199; acc: 79769.0/88391.0=0.9025
     Instance: 7000; Time: 3.90s; loss: 1257.8264; acc: 86063.0/95212.0=0.9039
     Instance: 7500; Time: 3.93s; loss: 1075.0858; acc: 92358.0/101941.0=0.9060
     Instance: 8000; Time: 3.90s; loss: 1118.7076; acc: 98639.0/108697.0=0.9075
     Instance: 8500; Time: 4.00s; loss: 1124.7306; acc: 105005.0/115547.0=0.9088
     Instance: 9000; Time: 3.78s; loss: 998.8595; acc: 110675.0/121622.0=0.9100
     Instance: 9500; Time: 3.99s; loss: 1119.5067; acc: 116939.0/128348.0=0.9111
     Instance: 10000; Time: 3.88s; loss: 973.6607; acc: 123008.0/134840.0=0.9123
     Instance: 10500; Time: 3.93s; loss: 1063.6829; acc: 129542.0/141819.0=0.9134
     Instance: 11000; Time: 4.15s; loss: 1083.4104; acc: 136347.0/149073.0=0.9146
     Instance: 11500; Time: 3.75s; loss: 921.5507; acc: 142283.0/155385.0=0.9157
     Instance: 12000; Time: 3.97s; loss: 1048.1671; acc: 148926.0/162497.0=0.9165
     Instance: 12500; Time: 3.93s; loss: 1027.8586; acc: 155284.0/169306.0=0.9172
     Instance: 13000; Time: 4.12s; loss: 1022.4437; acc: 162052.0/176513.0=0.9181
     Instance: 13500; Time: 4.00s; loss: 910.7379; acc: 168642.0/183503.0=0.9190
     Instance: 14000; Time: 4.11s; loss: 886.5571; acc: 175609.0/190843.0=0.9202
     Instance: 14500; Time: 3.97s; loss: 918.6670; acc: 181903.0/197517.0=0.9209
     Instance: 14987; Time: 4.17s; loss: 869.8843; acc: 188549.0/204567.0=0.9217
Epoch: 0 training finished. Time: 120.85s, speed: 124.01st/s,  total loss: 41396.6591034
totalloss: 41396.6591034
gold_num =  5942  pred_num =  5877  right_num =  4473
Dev: time: 8.28s, speed: 422.20st/s; acc: 0.9559, p: 0.7611, r: 0.7528, f: 0.7569
Exceed previous best f score: -10
Save current best model in file: sample_data/lstmcrf.0.model
gold_num =  5648  pred_num =  5714  right_num =  4102
Test: time: 7.76s, speed: 479.57st/s; acc: 0.9454, p: 0.7179, r: 0.7263, f: 0.7221
```
Python 3.6 on 1 epoch of CoNLL NER data AND `random.seed(a=42, version=1)`:
```
Epoch: 0/1
 Learning rate is setted as: 0.015
     Instance: 500; Time: 4.26s; loss: 4046.3888; acc: 5908.0/7047.0=0.8384
     Instance: 1000; Time: 4.50s; loss: 2509.3077; acc: 12080.0/14066.0=0.8588
     Instance: 1500; Time: 4.21s; loss: 2349.0080; acc: 18514.0/21345.0=0.8674
     Instance: 2000; Time: 4.00s; loss: 1825.2022; acc: 24550.0/28038.0=0.8756
     Instance: 2500; Time: 4.39s; loss: 1927.2833; acc: 30866.0/35058.0=0.8804
     Instance: 3000; Time: 3.76s; loss: 1698.8279; acc: 36632.0/41453.0=0.8837
     Instance: 3500; Time: 4.37s; loss: 1420.9238; acc: 42760.0/48128.0=0.8885
     Instance: 4000; Time: 4.08s; loss: 1667.7042; acc: 49387.0/55411.0=0.8913
     Instance: 4500; Time: 3.89s; loss: 1426.8074; acc: 55615.0/62186.0=0.8943
     Instance: 5000; Time: 4.55s; loss: 1412.5863; acc: 61796.0/68948.0=0.8963
     Instance: 5500; Time: 3.65s; loss: 1305.3924; acc: 67708.0/75431.0=0.8976
     Instance: 6000; Time: 4.05s; loss: 1430.7954; acc: 74210.0/82528.0=0.8992
     Instance: 6500; Time: 3.80s; loss: 1224.6866; acc: 80506.0/89323.0=0.9013
     Instance: 7000; Time: 3.92s; loss: 1244.6955; acc: 87209.0/96523.0=0.9035
     Instance: 7500; Time: 4.12s; loss: 1116.6483; acc: 93183.0/102949.0=0.9051
     Instance: 8000; Time: 3.76s; loss: 1074.9535; acc: 98909.0/109116.0=0.9065
     Instance: 8500; Time: 4.12s; loss: 1194.8343; acc: 105682.0/116376.0=0.9081
     Instance: 9000; Time: 3.96s; loss: 1049.8162; acc: 111943.0/123080.0=0.9095
     Instance: 9500; Time: 3.85s; loss: 940.8658; acc: 118025.0/129564.0=0.9109
     Instance: 10000; Time: 4.03s; loss: 1120.0469; acc: 124358.0/136375.0=0.9119
     Instance: 10500; Time: 4.01s; loss: 1034.5508; acc: 130663.0/143122.0=0.9129
     Instance: 11000; Time: 4.08s; loss: 1038.7787; acc: 137125.0/150016.0=0.9141
     Instance: 11500; Time: 4.33s; loss: 944.5785; acc: 143723.0/157026.0=0.9153
     Instance: 12000; Time: 4.36s; loss: 884.7583; acc: 150269.0/163970.0=0.9164
     Instance: 12500; Time: 3.94s; loss: 1013.7622; acc: 156720.0/170875.0=0.9172
     Instance: 13000; Time: 4.05s; loss: 999.2355; acc: 163022.0/177585.0=0.9180
     Instance: 13500; Time: 3.87s; loss: 807.0681; acc: 169078.0/183988.0=0.9190
     Instance: 14000; Time: 4.04s; loss: 931.6518; acc: 175608.0/190928.0=0.9198
     Instance: 14500; Time: 4.33s; loss: 920.7446; acc: 182225.0/197959.0=0.9205
     Instance: 14987; Time: 3.87s; loss: 910.0552; acc: 188429.0/204567.0=0.9211
Epoch: 0 training finished. Time: 122.14s, speed: 122.70st/s,  total loss: 41471.9580078125
totalloss: 41471.9580078125
gold_num =  5942  pred_num =  5315  right_num =  4277
Dev: time: 8.33s, speed: 419.45st/s; acc: 0.9529, p: 0.8047, r: 0.7198, f: 0.7599
Exceed previous best f score: -10
Save current best model in file: sample_data/lstmcrf.0.model
gold_num =  5648  pred_num =  5134  right_num =  3960
Test: time: 7.43s, speed: 500.54st/s; acc: 0.9471, p: 0.7713, r: 0.7011, f: 0.7346
```

There still remains a difference, even with the seed `version=1`. This post suggests that the way `random` is implemented, 
```
it's not reasonable to expect Random to give the same result on two different versions of Python, two different operating systems, or even two different computers. For all any of us knows, the next version of Python could implement a Random function that uses the system's microphone to generate a random sequence.
```
 It cites the `random` docs as a source for that assertion: https://docs.python.org/2/library/random.html, where it states 
```
The random module also provides the SystemRandom class which uses the system function os.urandom() to generate random numbers from sources provided by the operating system.
```

**Comment by jiesutd** [comment]
Thank you very much for your work! @abbottLane PR merged.

**Pull request merged**
